# 02 Data Structures and Libraries
## PRIMER



<br> <a href='#Lists'>1. Lists</a> 
<br> <a href='#Libraries'>2. Libraries</a>
<br> <a href='#numpyarray'>3. The `numpy array`</a>
	
 

 






<a id='Lists'></a>
# 1. Lists

<br> &emsp;&emsp; <a href='#Indexing'>1.1 Indexing</a> 
<br> &emsp;&emsp; <a href='#FindingLengthList'>1.2 FindingLengthList</a> 
<br> &emsp;&emsp; <a href='#SortingLists'>1.3 SortingLists</a> 
<br> &emsp;&emsp; <a href='#RemovingItemList'>1.4 Removing an Item from a List</a> 
<br> &emsp;&emsp; <a href='#AddingItemList'>1.5 Adding an Item to a List</a> 
<br> &emsp;&emsp; <a href='#ChangingListEntry'>1.6 Changing a List Entry</a> 
<br> &emsp;&emsp; <a href='#NestedDataStructures'>1.7 Nested Data Structures</a> 
<br> &emsp;&emsp; <a href='#IteratingLists'>1.8 Iterating over Lists</a> 
<br> &emsp;&emsp; <a href='#IndexingIterating'>1.9 Indexing when Iterating over Lists</a> 
<br> &emsp;&emsp; <a href='#enumerate'>1.10 `enumerate`</a>     
&emsp;&emsp; <a href='#zip'>1.11`zip`</a>

A list is a sequence of data. 

We call each item in the sequence an *element*. 

A list is constructed using square brackets:



In [1]:
a = [1, 2, 3]

A `range` can be converted to a list with the `list` function (casting).

In [2]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


A list can hold a mixture of types (`int`, `string`....).

In [3]:
a = [1, 2.0, "three"]

An empty list is created by

In [4]:
my_list = []

A list of length 5 with repeated values can be created by

In [5]:
my_list = ["Hello"]*5
print(my_list)

['Hello', 'Hello', 'Hello', 'Hello', 'Hello']


We can check if an item is in a list using the function `in`:


In [6]:
print("Hello" in my_list)
print("Goodbye" in my_list)

True
False


<a id='Indexing'></a>
## 1.1 Indexing

Lists store data in order.

We can select a single element or multiple elements of a list using the __index__ of the element(s).

You are familiar with this process; it is the same as selecting individual characters of a string:

In [7]:
word = "string"
letter = word[1]
print(letter)

t


In [8]:
lab_group0 = ["Sara", "Mari", "Quang", "Sam", "Ryo", "Nao", "Takashi"]

first_member = lab_group0[0]

print(first_member)

Sara


If we select multiple elements they are returned as a list:

In [9]:
lab_group0 = ["Sara", "Mari", "Quang", "Sam", "Ryo", "Nao", "Takashi"]

first_members = lab_group0[0:2]

print(first_members)

['Sara', 'Mari']


We can select the individual characters of a string using a second index.

For example to select the first letter of the second group member's name:

In [10]:
lab_group0 = ["Sara", "Mari", "Quang", "Sam", "Ryo", "Nao", "Takashi"]

letter = lab_group0[1][0]

print(letter)

M


<a id='ManipulatingLists'></a>
### Manipulating Lists 

There are many functions for manipulating lists.

Many of these functions apply to other data structures.











<a id='FindingLengthList'></a>
## 1.2 Finding the Length of a List

We can find the length (number of items) of a list using the function `len()`, by including the name of the list in the brackets. 

In the example below, we find the length of the list `lab_group0`. 

In [13]:
lab_group0 = ["Sara", "Mari", "Quang"]

size = len(lab_group0)

print("Lab group members:", lab_group0)

print("Size of lab group:", size)

print("Check the Python object type:", type(lab_group0))

Lab group members: ['Sara', 'Mari', 'Quang']
Size of lab group: 3
Check the Python object type: <class 'list'>


<a id='SortingLists'></a>
## 1.3 Sorting Lists

To sort the list we use the function `sorted()`.

#### Sorting Numerically

If the list contains numerical variables, the numbers is sorted in ascending order.

In [14]:
numbers = [7, 1, 3.0]

print(numbers)

numbers = sorted(numbers)

print(numbers)

[7, 1, 3.0]
[1, 3.0, 7]


__Note:__ We can sort a list with mixed numeric types (e.g. `float` and `int`). 

However, we cannot sort a list with types that cannot be sorted by the same ordering rule. 

(e.g. `numbers = sorted(["7", 1, 3.0])` causes an error.)

#### Sorting Alphabetically

If the list contains strings of alphabet characters, the list is sorted by alphabetical order. 

In [15]:
lab_group0 = ["Sara", "Mari", "Quang"]

print(lab_group0)

lab_group0 = sorted(lab_group0)

print(lab_group0)

['Sara', 'Mari', 'Quang']
['Mari', 'Quang', 'Sara']


As with `len()` we include the name of the list we want to sort in the brackets. 

`sort` is known as a 'method' of a `list`. 

If we suffix a list with `.sort()`, it performs an *in-place* sort.

In [16]:
lab_group0 = ["Sara", "Mari", "Quang"]

print(lab_group0)

#lab_group0 = sorted(lab_group0)
lab_group0.sort()

print(lab_group0)

['Sara', 'Mari', 'Quang']
['Mari', 'Quang', 'Sara']


__Try it yourself__

In the cell provided in your textbook create a list of __numeric__ or __string__ values.

Sort the list using `sorted()` __or__ `.sort()`.

Print the sorted list.

Print the length of the list using `len()`.

In [17]:
# Sorting a list

<a id='RemovingItemList'></a>
## 1.4 Removing an Item from a List

We can remove items from a list using the method `pop`.

We place the index of the element we wish to remove in brackets. 

In [18]:
lab_group0 = ["Sara", "Mari", "Quang", "Sam", "Ryo"]
print(lab_group0)

# Remove the second student from the list: lab_group (remember indexing starts from 0 so 1 is the second element)

lab_group0.pop(1)
print(lab_group0)

['Sara', 'Mari', 'Quang', 'Sam', 'Ryo']
['Sara', 'Quang', 'Sam', 'Ryo']


In [19]:
# By default, pop removes the last element

lab_group0.pop()
print(lab_group0)

['Sara', 'Quang', 'Sam']


In [20]:
# Pop can by used to assign the removed value to a variable name

group_member = lab_group0.pop(1)
print(lab_group0)
print(group_member)

['Sara', 'Sam']
Quang


<a id='AddingItemList'></a>
## 1.5 Adding an Item to a List

We can add items to a list using the method `insert`.

We place the desired index of new element in brackets. 

In [21]:
# Add new student "Mark" to the list
lab_group0.insert(2, "Mark")
print(lab_group0)

['Sara', 'Sam', 'Mark']


We can add items at the end of a list using the method `append`.

We place the element we want to add to the end of the list in brackets. 

In [22]:
# Add new student "Lia" at the end of the list
lab_group0.append("Lia")
print(lab_group0)

['Sara', 'Sam', 'Mark', 'Lia']


<a id='ChangingListEntry'></a>
## 1.6 Changing a List Entry.
We can change the entry of a list using indexing.

In [23]:
lab_group0[3] = "Am"
print(lab_group0)

# Adding and removing items from a list.

['Sara', 'Sam', 'Mark', 'Am']


__Try it yourself__

In the cell provided in your textbook.

Remove "Sara" from the list.

Print the new list.

Add a new lab group member, Tom, to the list.

Print the new list.

In [24]:
lab_group0 = ["Sara", "Mari", "Quang", "Sam", "Ryo"]
print(lab_group0)

# Adding and removing items from a list.

['Sara', 'Mari', 'Quang', 'Sam', 'Ryo']


<a id='NestedDataStructures'></a>
## 1.7 Nested Data Structures: Lists of Lists

A *nested list* is a list within a list. 

(Recall *nested loops* from the last seminar 1; Control Flow). 



To access a __single element__ we need as many indices as there are levels of nested list. 

This is more easily explained with an example:

`lab_groups` is a nested list containing the lists:
 - `lab_group0`
 - `lab_group1`
 - `lab_group2`

In [25]:
lab_group0 = ["Sara", "Mika", "Ryo", "Am"]
lab_group1 = ["Hemma", "Miri", "Quy", "Sajid"]
lab_group2 = ["Adam", "Yukari", "Farad", "Fumitoshi"]

lab_groups = [lab_group0, lab_group1, lab_group2]

To select and element from `lab_group1` we:
- first give the index of `lab_group1` in th list `lab_groups`
- second give the index of the element within `lab_group1`

In [26]:
group = lab_groups[1]
print(group)

name = lab_groups[1][2]
print(name)

['Hemma', 'Miri', 'Quy', 'Sajid']
Quy


<a id='IteratingLists'></a>
## 1.8 Iterating over Lists

Looping over each item in a list is called *iterating*. 

To iterate over a list of the lab group we  can use a `for` loop.



In the followig example, each iteration, variable `d` takes the value of the next item in the list:

In [27]:
for d in [1, 2.0, "three"]:    
    print("the value of d is:", d)

the value of d is: 1
the value of d is: 2.0
the value of d is: three


We could also express this as:

In [28]:
data = [1, 2.0, "three"]

for d in data:    
    print("the value of d is:", d)

the value of d is: 1
the value of d is: 2.0
the value of d is: three


Iterating backwards over a list can be acheived using the built in `reversed` function.

In [29]:
data = [1, 2.0, "three"]

for d in reversed(data):    
    print("the value of d is:", d)

the value of d is: three
the value of d is: 2.0
the value of d is: 1


__Try it yourself__


In the cell provided in your textbook *iterate* over the list `data = [1, 2.0, "three"]`.

Each time the code loops:
1. print the value of data __cast as a string__ (Seminar 1 Data Types and Operators)
1. print the variable type<br>(to demonstrate that the variable has been cast. Note that otherwise the variable appears to remain unchanged).

In [30]:
# Iterate over a list and cast each item as a string
data = [1, 2.0, "three"]

<a id='IndexingIteratingLists'></a>
## 1.9 Indexing when Iterating over Lists
Indexing can be useful when iterating over a list.



For example, we can select a range of elements to iterate over:

In [31]:
lab_group0 = ["Sara", "Mari", "Quang", "Sam", "Ryo", "Nao", "Takashi"]

for member in lab_group0[2:5]:    
    print("name:", member)

name: Quang
name: Sam
name: Ryo


A third value can used to choose a step size (similar to `range()`).

For example, if we want to choose every other lab member we use step size, 2:

In [32]:
lab_group0 = ["Sara", "Mari", "Quang", "Sam", "Ryo", "Nao", "Takashi"]

for member in lab_group0[::2]:    
    print("name:", member)

name: Sara
name: Quang
name: Ryo
name: Takashi


__Note:__<br>
Some data structures that support *iterating* but do not support *indexing*.

e.g. dictionaries, which we will learn about later. 

When possible, it is better to iterate over a list rather than use indexing.

<a id='enumerate'></a>
## 1.10 `enumerate()`
The function `enumerate` can be used to return the index of each element.
<br>This information is cast as a list to allow us to read it.

In [33]:
lab_group0 = ["Sara", "Mari", "Quang", "Sam", "Ryo", "Nao", "Takashi"]
a = enumerate(lab_group0)
b = list(enumerate(lab_group0))
print(a)
print(b)



[(0, 'Sara'), (1, 'Mari'), (2, 'Quang'), (3, 'Sam'), (4, 'Ryo'), (5, 'Nao'), (6, 'Takashi')]


In [34]:
string = "string"
a = list(enumerate(string))
print(a)

[(0, 's'), (1, 't'), (2, 'r'), (3, 'i'), (4, 'n'), (5, 'g')]


<a id='zip'></a>
## 1.11 Iterating Over Multiple Lists Using `zip()`
It can be very useful to iterate through multiple lists within the same loop. than one list.

For example if we have a list of group members and a list of their scores for an assignemt, we can print the score that corresponds to each lab member:

In [35]:
lab_group0 =  ["Sara", "Mari", "Quang", "Sam", "Ryo", "Nao", "Takashi"]

assignment1 = [72, 56, 65, 52, 71, 60]

for member, score in zip(lab_group0, assignment1):    
    
    print(member, ": score =", score)

Sara : score = 72
Mari : score = 56
Quang : score = 65
Sam : score = 52
Ryo : score = 71
Nao : score = 60


In this example 

`member` is the name given to the *current* value from the list `lab_group0`

`score` is the names given to the *current* value from the list `assignment1`.  


We can include any number of lists in `zip`.

For example it may be useful to print the combined score a lab member has achieved for all assigments this semester:

In [36]:
lab_group0 =  ["Sara", "Mari", "Quang", "Sam", "Ryo", "Nao", "Takashi"]

assignment1 = [72, 56, 65, 52, 71, 60]
assignment2 = [52, 61, 73, 55, 62, 55]
assignment3 = [71, 71, 70, 66, 61, 71]

for member, score1, score2, score3 in zip(lab_group0, 
                                          assignment1, 
                                          assignment2, 
                                          assignment3):    
    print(member, ": score =", (score1 + score2 + score3))

Sara : score = 195
Mari : score = 188
Quang : score = 208
Sam : score = 173
Ryo : score = 194
Nao : score = 186


<a id='Libraries'></a>
# 2. Libraries

<br> &emsp;&emsp; <a href='#StandardLibrary'>__2.1 The Standard Library__</a> 
<br> &emsp;&emsp; <a href='#Packages'>__2.2 Packages__ </a>  
&emsp;&emsp; <a href='#Namespaces'>__2.3 Namespaces__</a> 
<br> &emsp;&emsp; <a href='#ImportingFunction'>__2.4 Importing a Function__</a> 

   

<a id='StandardLibrary'></a>
## 2.1 The Standard Library

Python has a large standard library. 

e.g. `print()` takes the __input__ in the parentheses and __outputs__ a visible representation.

They are listed on the Python website:
https://docs.python.org/3/library/functions.html

__Function:__
<br>A piece of code that is called by name. 
<br>It can be *passed* data to operate on (i.e., the parameters) and can optionally *return* data (the return value). 

__Example__
```Python
sorted([5, 2, 3, 1, 4])
```

__Method:__
<br>A method is a piece of code that is called by name.
<br>It is already associated with an object type (e.g. a list) so it is expressed after a . dot at the end of the object name. 
<br>It mostly behaves the same as a function  except:  
- It is automatically passed for the object which it is attached to.
- (It can only operate on objects that contain the method. It can operate on data insde of that class.)  

__Example__
```Python
a = [1, 5, 2, 7, 5]
a.sort()
```

<a id='Packages'></a>
## 2.2 Packages

The standard library tools are available in any Python environment.

More specialised libraries, called packages, are available for more specific tasks 
<br>e.g. solving trigonometric functions.

Packages contain functions and constants.  

We install the packages to use them.   



Two widely used packages for mathematics, science and engineeirng are `NumPy` and `SciPy`.

These are already installed as part of Anaconda.

A package is a collection of Python modules: 
- a __module__ is a single Python file
- a __package__ is a directory of Python modules.<br>(It contains an __init__.py file, to distinguish it from folders that are not libraries).

The files that are stored on your computer when Pygame is installed:
<br>https://github.com/pygame/pygame

<a id='ImportingPackage'></a>
### Importing a Package

To use an installed package, we  simply `import` it.

We only need to import the package once.
<br>The `import` statement must appear before the use of the package in the code so all packages are usually imported at the start of the program. 

        import numpy 

We can then use variable and functions defined within that package by prefixing them with the name of the package:

In [37]:
import numpy 

After this, any constant, variable or function from the package can be used by prefixing it with the name of the package:

Any constant in `numpy` can be called as:

        `numpy.constant`.
        

Any function in `numpy` can be called as:

        `numpy.function()`
        




In [38]:
# pi
print(numpy.pi)

x = 1

# Trigonometric functions e.g. cosine
y = numpy.cos(x)
print(y)

# Exponential function
print(numpy.exp(1))

3.141592653589793
0.5403023058681398
2.718281828459045


There are a many mathematical functions available. <br>
https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

We can change the name of a package e.g. to keep our code short and neat.

Using the __`as`__ keyword:

In [39]:
import numpy as np

# Natural logarithmic function
print(np.log(10))

# Base 10 logarithmic function
print(np.log10(10))

2.302585092994046
1.0


<a id='Namespaces'></a>
## 2.3 Namespaces
<br>By prefixing `cos` with `np`, we are using a *namespace* (which in this case is `np`).



The namespace shows we want to use the `cos` function from the Numpy package.

If `cos` appears in more than one package we import, then there will be more than one `cos` function available.

We must make it clear which `cos` we want to use. 




Often, functions with the same name, from different packages, will use a different algorithms for performing the same or similar operation. 

They may vary in speed and accuracy. 

In some applications we might need an accurate method for computing the square root, for example, and the speed of the program may not be important. For other applications we might need speed with an allowable compromise on accuracy.


Below are two functions, both named `sqrt`. 

Both functions compute the square root of the input.

 - `math.sqrt`, from the package, `math`, gives an error if the input is a negative number. It does not support complex numbers.
 - `cmath.sqrt`, from the package, `cmath`, supports complex numbers.


In [40]:
import math
import cmath
print(math.sqrt(4))
#print(math.sqrt-5)
#print(cmath.sqrt(-5))

2.0


Two developers collaborating on the same program might choose the same name for two functions that perform similar tasks. 

If these functions are in different modules, there will be no name clash since the module name provides a 'namespace'. 

<a id='ImportingFunction'></a>
## 2.4 Importing a Function
Single functions can be imported without importing the entire package e.g. use:

        from numpy import cos

instead of:

        import numpy 

After this you call the function without the numpy prefix: 

In [41]:
from numpy import cos

cos(x)

0.5403023058681398

In [42]:
from numpy import cos

cos(x)

0.5403023058681398

In [43]:
from numpy import cos

cos(x)

0.5403023058681398

Be careful when doing this as there can be only one definition of each function.
In the case that a function name is already defined, it will be overwritten by a more recent definition. 

In [44]:
from cmath import sqrt
print(sqrt(-1))
from math import sqrt
#print(sqrt(-1))

1j


A potential solution to this is to rename individual functions or constants when we import them:

In [45]:
from numpy import cos as cosine

cosine(x)

0.5403023058681398

In [46]:
from numpy import pi as pi
pi

3.141592653589793

This can be useful when importing functions from different modules:

In [47]:
from math import sqrt as square_root
from cmath import sqrt as complex_square_root

print(square_root(4))
print(complex_square_root(-1))

2.0
1j


Function names should be chosen wisely.
 - relevant
 - concise

<a id='numpyarray'></a>
## The `numpy array`
<br> &emsp;&emsp; <a href='#MultiDimensionalArrays'>3.1 Multi-Dimensional Arrays</a> 
<br> &emsp;&emsp; <a href='#CreatingNumpyArray'>3.2 Creating a `numpy array`</a> 
<br> &emsp;&emsp; <a href='#IndexingMultiDimensionalArrays'>3.3 Indexing into Multi-Dimensional Arrays</a> 
<br> &emsp;&emsp; <a href='#BooleanArrayIndexing'>3.4 Boolean Array Indexing</a> 
<br> &emsp;&emsp; <a href='#IteratingMultiDimensionalArrays'>3.5 Iterating over Multi-Dimensional Arrays</a> 
<br> &emsp;&emsp; <a href='#ManipulatingArrays'>3.6 Manipulating Arrays</a>  
&emsp;&emsp; <a href='#StackingFunctions'>3.7 Stacking Functions</a> 
<br> &emsp;&emsp; <a href='#ImportingData'>3.8 Importing Data from  a .csv File to a `numpy array`</a> 

A numpy array is a grid of values, *all of the same type*.



### Why do we need another data structure?

Python lists hold 'arrays' of data. 

Lists are very flexible. e.g. holding mixed data type.

There is a trade off between flexibility and performance e.g. speed.

Science engineering and mathematics problems often involve large amounts of data and numerous operations. 

We therefore use specialised functions and data structures for numerical computation.

To create an array we use the Numpy `np.array()` function.

We can create an array in a number of ways.

For example we can convert a list to an array. 

In [48]:
c = [4.0, 5, 6.0]

d = np.array(c) 

print(type(c))
print(type(d))
print(d.dtype)

print(c + c)
print(d + d)

<class 'list'>
<class 'numpy.ndarray'>
float64
[4.0, 5, 6.0, 4.0, 5, 6.0]
[ 8. 10. 12.]


The method `dtype` tells us the type of the data contained in the array.



<a id='MultiDimensionalArrays'></a>
## 3.1 Multi-Dimensional Arrays






Unlike the data types we have studied so far, arrays can have multiple dimensions.

__`shape`:__ a *tuple* of *integers* giving the *size* of the array along each *dimension*.

__`tuple`:__ A data structure from which you cannot add or remove elements without creating a new tuple (e.g. connecting two tuples). <br>You cannot change the value of a single tuple element e.g. by indexing. <br>A tuple is created by enclosing a set of numbers in () parentheses. 

We define the dimensions of an array using square brackets

In [49]:
# 1-dimensional array
a = np.array([1, 2, 3])

# 2-dimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])

b = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(a.shape)
print(b.shape)


(3,)
(2, 3)


In [50]:
# 2-dimensional array
c = np.array([[1, 2, 3]])

# 2-dimensional array
d = np.array([[1], 
              [4]])

print(c.shape)
print(d.shape)

(1, 3)
(2, 1)


In [51]:
# 3-dimensional array

c = np.array(
    [[[1, 1],
      [1, 1]],
    
     [[1, 1],
      [1, 1]]])

print(c.shape)

c = np.array(
    [[[1, 1],
      [1, 1]],
     
     [[1, 1],
      [1, 1]],
    
     [[1, 1],
      [1, 1]]])

print(c.shape)

(2, 2, 2)
(3, 2, 2)


In [52]:
# 3-dimensional array

c = np.array(
    [[[1, 1],
      [1, 1]],
    
     [[1, 1],
      [1, 1]]])

# 4-dimensional array
d = np.array(
    [[[[1, 1],
       [1, 1]],
      
      [[1, 1],
       [1, 1]]],


      [[[1, 1],
       [1, 1]],
      
      [[1, 1],
       [1, 1]]]])

print(c.shape)
print(d.shape)

(2, 2, 2)
(2, 2, 2, 2)


<a name="CreatingNumpyArray"></a>
## 3.2 Creating a `numpy array`



We don't always have to manually create the individual elements of an array.

There are several other ways to do this.

For example, if you don’t know what data you want to put in your array you can initialise it with placeholders and load the data you want to use later. 


In [53]:
# Create an array of all zeros
# The zeros() function argument is the shape.
# Shape: tuple of integers giving the size along each dimension.

a = np.zeros(5)
print(a)

print()

a = np.zeros((2,2))   
print(a)  

[0. 0. 0. 0. 0.]

[[0. 0.]
 [0. 0.]]


In [54]:
# Create an array of all ones

b = np.ones(5)
print(b)

print()

b = np.ones((1, 4))    
print(b) 


[1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]]


In [55]:
# Create an array of elements with the same value 
# The full() function arguments are
# 1) Shape: tuple of integers giving the size along each dimension.
# 2) The constant value

y = np.full((1,1), 3)
print(y)
print(y.shape)

print()

y = np.full((2,2), 4)   
print(y)  

[[3]]
(1, 1)

[[4 4]
 [4 4]]


In [56]:
# Create a 1D array of evenly spaced values
# The arange() function arguments are the same as the range() function. 
# Shape: tuple of integers giving the size along each dimension.

z = np.arange(5,10)
print(z)

print()

z = np.arange(5, 10, 2)   
print(z)  

[5 6 7 8 9]

[5 7 9]


In [57]:
# Create a 1D array of evenly spaced values
# The linspace() function arguments are
# The lower limit of the range of values
# The upper limit of the range of values (inclusive)
# The desired number of equally spaced values

z = np.linspace(-4, 4, 5)
print(z) 

[-4. -2.  0.  2.  4.]


In [58]:
# Create an empty matrix
# The empty() function argument is the shape.
# Shape: tuple of integers giving the size along each dimension.
import numpy as np
x = np.empty((4))
print(x)

print()

x = np.empty((4,4))
print(x)

[4. 2. 2. 4.]

[[0.00000000e+000 8.23153977e-067 1.51903910e-047 4.66315783e-033]
 [4.79582321e-037 1.00441435e-042 2.94879474e+179 9.43693933e+164]
 [1.33689898e+165 0.00000000e+000 1.28822975e-231 1.28822975e-231]
 [1.28822975e-231 1.28822975e-231 3.45845952e-323 0.00000000e+000]]


In [59]:
# Create a constant array
# The second function argument is the constant value

c = np.full(6, 8)
print(c)

print()

c = np.full((2,2,2), 7)  
print(c)               


[8 8 8 8 8 8]

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


<a id='IndexingMultiDimensionalArrays'></a>
## 3.3 Indexing into Multi-Dimensional Arrays



We can index into an array exactly the same way as the other data structures we have studied.

In [60]:
x = np.array([1, 2, 3, 4, 5])

# Select a single element
print(x[4])

# Select elements from 2 to the end
print(x[2:])

5
[3 4 5]


For an n-dimensional (nD) matrix we need n index values to address an element or range of elements.

Example: The index of a 2D array is specified with two values:
- first the row index
- then the column index.

Note the order in which dimensions are addressed.

In [61]:
# 2 dimensional array

y = np.array([[1, 2, 3], 
              [4, 5, 6]])


# Select a single element
print(y[1,2])

# Select elements that are both in rows 1 to the end AND columns 0 to 2 
print(y[1:, 0:2])

6
[[4 5]]


We can address elements by selecting a range with a step: 

For example the index:

`z[0, 0:]`

selects every element of row 0 in array, `z`

The index:

`z[0, 0::2]`

selects every *other* element of row 0 in array, `z`

In [62]:
# 2 dimensional array

z = np.zeros((4,8))

# Change every element of row 0
z[0, 0:] = 10

# Change every other element of row 1
z[1, 0::2] = 10

print(z)

[[10. 10. 10. 10. 10. 10. 10. 10.]
 [10.  0. 10.  0. 10.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [63]:
z = np.zeros((4,8))

# Change the last 4 elements of row 2, in negative direction
# You MUST include a step to count in the negative direction
z[2, -1:-5:-1] = 10

# Change every other element of the last 6 elements of row 3
# in negative direction
z[3, -2:-7:-2] = 10

print(z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 10. 10. 10. 10.]
 [ 0.  0. 10.  0. 10.  0. 10.  0.]]


In [64]:
# 3-dimensional array

c = np.array(
    [[[2, 1, 4],
      [2, 6, 8]],
    
     [[0, 1, 5],
      [7, 8, 9]]])

print(c[0, 1, 2])



8


Where we want to select all elements in one dimension we can use :

__Exception__: If it is the last element , we can omit it. 

In [65]:
print(c[0, 1])

print(c[0, :, 1])

[2 6 8]
[1 6]


<a name="BooleanArrayIndexing"></a>
## 3.4 Boolean Array Indexing




Recall that we can use *conditional operators* to check the value of a single variable against a condition.

The value returned is a Boolean True or False value.


In [66]:
a = 4
print('a < 2:', a < 2)
print('a > 2:', a > 2)

a < 2: False
a > 2: True


If we instead use *conditional operators* to check the value of an array against a condition.

The value returned is an *array* of Boolean True or False values.

In [67]:
a = np.array([[1,2], 
              [3, 4], 
              [5, 6]])

idx = a > 2

print(idx)


[[False False]
 [ True  True]
 [ True  True]]


A particular elements of an array can be are specified by using a boolean array as an index. 

Only the values of the array where the boolean array is `True` are selected. 

The varaible `idx` can therefore now be used as the index to select all elements greater than 2.

In [68]:
print(a[idx])   

[3 4 5 6]


To do the whole process in a single step

In [69]:
print(a[a > 2]) 

[3 4 5 6]


To apply multiple conditions, use () parentheses to sperate different conditions.

Use `&` for elementwise `and`.

Use `|` for elementwise `or`.

In [70]:
x = np.array([[4, 2, 3, 1],
              [2, 4, 2, 8],
              [2, 3, 3, 27],
              [4, 1, 4, 64]])

# elements of x that are greater then 2 AND less than 10
print(x[(2 < x) & (x < 10)])

# elements of x that are less then 2 OR greater than 10
print(x[(2 < x) & (x < 10)])

[4 3 4 8 3 3 4 4]
[4 3 4 8 3 3 4 4]


Multiple conditions can also be applied to a subsection of an array.
<br>For example to select elements $>2$ and $<4$ in the first row of `x` only (`x[0]`):

In [71]:
x = np.array([[4, 2, 3, 1],
              [2, 4, 2, 8],
              [2, 3, 3, 27],
              [4, 1, 4, 64]])


print(x[0][(2 < x[0]) & (x[0] < 4)])


[3]


<a id='IteratingMultiDimensionalArrays'></a>
## 3.5 Iterating over Multi-Dimensional Arrays

We can iterate over a 1D array in the same way as the data structures we have previously studied.

In [72]:
A = np.array([1, 2, 3, 4, 5])

In [73]:
for a in A:
    print(a)

1
2
3
4
5


To loop through individual elements of a multi-dimensional array, we use a nested loop for each dimension of the array.

In [74]:
B = np.array([[1, 2, 3], 
              [4, 5, 6]])

for row in B:
    print("-----")
    for col in row:
        print(col)

-----
1
2
3
-----
4
5
6


<a id='ManipulatingArrays'></a>
## 3.6 Manipulating Arrays




We can use many of the same operations to manipulate arrays as we use for lists.

However, it is important to note a few subtle differences in how array manipulations behave. 

In [75]:
# Length of an array

a = np.array([1, 3, 4, 17, 3, 21, 2, 12])

b = np.array([[1, 3, 4, 17],
              [3, 21, 2, 12]])


print(len(a))
print(len(b))



8
2


Note the length is the length of the first dimension (e.g. indexing). 

In [76]:
# Sort an array

a = np.array([1, 3, 4, 17, 3, 21, 2, 12])

b = np.array([[1, 3, 4, 17],
              [3, 21, 2, 12]])

# The function sorted applies to 1D data structures only
print(sorted(a))
print(sorted(b[1]))

# The method sort() applies to arrays of any size
a.sort()
b.sort()

print(a)
print(b)

[1, 2, 3, 3, 4, 12, 17, 21]
[2, 3, 12, 21]
[ 1  2  3  3  4 12 17 21]
[[ 1  3  4 17]
 [ 2  3 12 21]]


Arrays are *immutable* (unchangeable).

Technically you cannot add or delete items of an array. 

However, you can make a *new* array (which may have the same name as the original array), with the values ammended as required: 

<a id='AppendingArrays'></a>
#### Appending Arrays 
Appending connects array-like (integer, list....) value  to the *end* of the original array. 

By default, 2D arrays are appended as if joining lists.
The new array is a 1D array

In [77]:
# 2D array
a = np.array([[0], [1], [2]])
print(a)
print()

# 2D array
b = np.array([[3], [4]])
print(b)
print()

# 1D array
c = np.array([3, 4])
print(b)
print()

# integer
d = 1

print(f"original 2D array shapes: a = {a.shape}, b = {b.shape}")
print()

X = np.append(a, b)
print(X)
print(f"new array shape: {a.shape}")
print()

X = np.append(b, d)
print(X)
print(f"new array shape: {a.shape}")
print()

X = np.append(c, d)
print(X)
print(f"new array shape: {a.shape}")
print()

[[0]
 [1]
 [2]]

[[3]
 [4]]

[[3]
 [4]]

original 2D array shapes: a = (3, 1), b = (2, 1)

[0 1 2 3 4]
new array shape: (3, 1)

[3 4 1]
new array shape: (3, 1)

[3 4 1]
new array shape: (3, 1)



The axis on which to append an array can be optionally specified.

e.g. 2D array:
 - 0: columns
 - 1: rows

The arrays must have the same shape, except in the dimension corresponding to the specified axis 

In [78]:
# 2D array
a = np.array([[0], [1], [2]])
print(a)
print()

# 2D array
b = np.array([[3], [4]])
print(b)
print()

new2d = np.append(a, b, axis=0)
print(new2d)
print(f"new array shape: {new2d.shape}")

[[0]
 [1]
 [2]]

[[3]
 [4]]

[[0]
 [1]
 [2]
 [3]
 [4]]
new array shape: (5, 1)


For example, in the cell above, if you change `axis=0` to `axis=1`, 
<br>you are trying to connect the side of `a` with length=3 to the side of `b` with length=2.

There are dedicated functions to simplify joining or merging arrays.
<br>If you are interested to expeirment further with joiing arrays you can try out the following functions:
 - `np.concatenate()` : Joins a sequence of arrays along an existing axis.
 - `np.vstack()` or `np.r_[]`: Stacks arrays row-wise
 - `np.hstack()` : Stacks arrays horizontally
 - `np.column_stack()` or `np.c_[]` : Stacks arrays column-wise
Refer to last week's seminar for how to inpterpret the function documentation. 

It can also be useful to remove individual (single or multiple) elements.

For example, the following expand the locations within the array that you can change beyond the location at the *end* of the array.

<a id='AddingElementsArray'></a>
#### Adding Elements to an Array

In [79]:
# Add items to an array
# The insert() function arguments are
# 1) The array to insert to
# 2) The index of the inserted element
# 3) The value of the inserted element

a = ([1, 2, 3])
a = np.insert(a, 1, 4)
print(a)

[1 4 2 3]


Notice that, again, the output is a 1D aray by default

In [80]:
# Add items to an array

b = np.array([[1, 1], 
              [2, 2], 
              [3, 3]])

print(f"original array shape: {b.shape}")

b = np.insert(b, 1, [4, 4])

print(b)

print(f"new array shape: {b.shape}")

original array shape: (3, 2)
[1 4 4 1 2 2 3 3]
new array shape: (8,)


To preserve the multi-dimensional structure of an array, we can specify the axis on which to insert an element or range of elements. 
<br> In the example below, a column is inserted at element 1 of axis 1. 

In [81]:
# Add items to an array

b = np.array([[1, 1], 
              [2, 2], 
              [3, 3]])

b = np.insert(b, 1, [3, 2, 1], axis=1)
print(b)

[[1 3 1]
 [2 2 2]
 [3 1 3]]


Notice what happens when we insert a *single* value on a specified axis

In [82]:
b = np.insert(b, 1, 4, axis=1)
print(b)

[[1 4 3 1]
 [2 4 2 2]
 [3 4 1 3]]


This behaviour is due to a very useful property called *broadcasting*. 
<br>We will study the rules governing broadcasting later in this seminar. 

<a id='DeletingItemsArray'></a>
#### Deleting Items from an Array

In [83]:
# Items are deleted from their position in a 1D array by default

z = np.array([1, 3, 4, 5, 6, 7, 8, 9])


z = np.delete(z, 3)
print(z)

z = np.delete(z, [0, 1, 2])
print(z)


[1 3 4 6 7 8 9]
[6 7 8 9]


In [84]:
# Again, axes to delete can be optionally specified:

z = np.array([[1, 3, 4, 5], [6, 7, 8, 9]])
print(z)
print()

z = np.delete(z, 3, axis=1)
print(z)
print()

z = np.delete(z, [0, 1, 2], axis=1)
print(z)
print()

[[1 3 4 5]
 [6 7 8 9]]

[[1 3 4]
 [6 7 8]]

[]



<a name="ChangingItemsArray"></a>
#### Changing Items in an Array


In [85]:
c = np.array([1, 2, 3])
c[1] = 4
print(c)

[1 4 3]


<a id='StackingFunctions'></a>
## 3.7 Stacking Functions




If performing multiple functions on a variable or data structure, operations can be stacked to produce shorter code.


In [ ]:
a = range(10)
a = list(a)
a = np.cos(a)
a = np.sum(a)
print(a)

a = np.sum(np.cos(list(range(10))))
print(a)

<a id='ImportingData'></a>
## 3.8 Importing Data from  a .csv File to a `numpy array`

Real data is often stored in .csv files (typically viewed in Excel).

csv files are simply comma separated values (although the values can be separated or *delimited* by other things than commas).

A Numpy array can be a very useful way to store and manipulate data e.g. the raw data from an experiment.

Numerical data can be loaded from a .txt or .data. or .csv file using the function; `numpy.loadtxt`.

The file to be loaded must be in the same directory as your python program.
<br>Otherwise you must specify the the full path to the data file using / to seperate directory names. 
<br>The filename (or path plus filename) needs to be between "" quotation marks. 

For example the file data.dat in the folder sample_data contains:
>0.000 1.053 2.105 3.158 4.211<br>
74.452 48.348 68.733 59.796 54.123

The default delimiter is a space.
<br>The default data type to output is an array of floating point values. 

In [ ]:
A = np.loadtxt('sample_data/sample_data.dat')
print(A)
print(type(A))
print(A[0][1])

The __delimiter__ should (sometimes) be specified.
<br>This tells Python how to separate the data into the individual elements of an array. 
<br>The default delimiter is a space.
<br>(Data separated by spaces will be automatically be assigned different indices).

The __data type__ should (sometimes) be specified.
<br>This tells Python how to separate the data into the individual elements of an array. 
<br>The default data type is `float`.
<br>If your data contains items that cannot be expressed as a float, importing it will cause an error unless the data-type is specified.
<br>Mixed data types can be imported as `string` values. 

For example, the data in sample_student_data.txt:
- is seperated by tabs (`/t`) 
- cannot all be converted to float data (in some columns)

```Python
Subject	Sex	DOB	Height	Weight	BP
(ID)	M/F	dd/mm/yy	m	kg	mmHg
JW-1	M	19/12/1995	1.82	92.4	119/76
JW-2	M	11/01/1996	1.77	80.9	114/73
JW-3	F	02/10/1995	1.68	69.7	124/79
JW-6	M	06/07/1995	1.72	75.5	110/60
JW-7	F	28/03/1996	1.66	72.4	-
JW-9	F	11/12/1995	1.78	82.1	115/75
JW-10	F	07/04/1996	1.6	45	-/-
JW-11	M	22/08/1995	1.72	77.2	97/63
JW-12	M	23/05/1996	1.83	88.9	105/70
JW-14	F	12/01/1996	1.56	56.3	108/72
JW-15	F	01/06/1996	1.64	65	99/67
JW-16	M	10/09/1995	1.63	73	131/84
JW-17	M	17/02/1996	1.67	89.8	101/76
JW-18	M	31/07/1996	1.66	75.1	-/-
JW-19	F	30/10/1995	1.59	67.3	103/69
JW-22	F	09/03/1996	1.7	45	119/80
JW-23	M	15/05/1995	1.97	89.2	124/82
JW-24	F	01/12/1995	1.66	63.8	100/78
JW-25	F	25/10/1995	1.63	64.4	-/-
JW-26	M	17/04/1996	1.69	55	121/82
```

In [ ]:
np.loadtxt('sample_data/sample_student_data.txt', delimiter="\t", dtype=str)

Regions can be selected, for example to select only numerical data. 

`skiprows` skips the first n lines. 

`usecols` specifies which columns to read, with 0 being the first. 
<br>For example, usecols = (1,4,5) will extract the 2nd, 5th and 6th columns.

In [ ]:
import numpy as np
np.loadtxt('sample_data/sample_student_data.txt', dtype=float, skiprows=9, usecols=(3,4))

We only need to import a package once, at the start of the program or notebook.

<a id='Summary'></a>
# Summary

- Python has an extensive __standard library__ of built-in functions. 
- More specialised libraries of functions and constants are available. We call these __packages__. 
- Packages are imported using the keyword `import`
- The function documentation tells is what it does and how to use it.
- When calling a library function it must be prefixed with a __namespace__ is used to show from which package it should be called.  
- The magic function `%timeit` can be used to time the execution of a function. 


